
  CREATE TABLE "CLIENTE" 
   (	"ID_CLIENTE" NUMBER(*,0), 
	"RUT" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"AP_PATERNO" VARCHAR2(100 BYTE), 
	"AP_MATERNO" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"COD_COMUNA" NUMBER(*,0), 
	"COD_TIPO_CLIENTE" NUMBER(*,0), 
	"TELEFONO" VARCHAR2(50 BYTE), 
	"MAIL" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CLIENTE_PESOS
--------------------------------------------------------

  CREATE TABLE "CLIENTE_PESOS" 
   (	"ID_CLIENTE" NUMBER, 
	"RUT_CLIENTE" VARCHAR2(12 BYTE), 
	"NOMBRE" VARCHAR2(200 BYTE), 
	"TIPO_CLIENTE" VARCHAR2(20 BYTE), 
	"MONTO_CREDITOS" NUMBER, 
	"MONTO_PESOS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table COMUNA
--------------------------------------------------------

  CREATE TABLE "COMUNA" 
   (	"COD_COMUNA" NUMBER(*,0), 
	"COMUNA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CONTRATO
--------------------------------------------------------

  CREATE TABLE "CONTRATO" 
   (	"ID_CONTRATO" NUMBER(*,0), 
	"FECHA_CONTRATO" DATE, 
	"ID_CLIENTE" NUMBER(*,0), 
	"ID_EJECUTIVO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CREDITO
--------------------------------------------------------

  CREATE TABLE "CREDITO" 
   (	"ID_CREDITO" NUMBER(*,0), 
	"ID_CONTRATO" NUMBER(*,0), 
	"COD_PRODUCTO" NUMBER(*,0), 
	"MONTO" NUMBER(10,0), 
	"CANTIDAD_CUOTAS" NUMBER(*,0), 
	"FECHA_INICIO" DATE, 
	"FECHA_TERMINO" DATE, 
	"COD_TIPO_CREDITO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table CUENTA
--------------------------------------------------------

  CREATE TABLE "CUENTA" 
   (	"ID_CUENTA" NUMBER(*,0), 
	"NRO_CUENTA" NUMBER(10,2), 
	"COD_TIPO_CUENTA" NUMBER(*,0), 
	"SALDO" NUMBER(10,2), 
	"ID_CONTRATO" NUMBER(*,0), 
	"COD_PRODUCTO" NUMBER(*,0), 
	"CUPO_LINEA_CREDITO" NUMBER(10,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table DETALLE_CONTRATO
--------------------------------------------------------

  CREATE TABLE "DETALLE_CONTRATO" 
   (	"ID_CONTRATO" NUMBER(*,0), 
	"COD_PRODUCTO" NUMBER(*,0), 
	"MANT_MENSUAL" NUMBER(10,2)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EJECUTIVO
--------------------------------------------------------

  CREATE TABLE "EJECUTIVO" 
   (	"ID_EJECUTIVO" NUMBER(*,0), 
	"RUT" VARCHAR2(10 BYTE), 
	"NOMBRE" VARCHAR2(100 BYTE), 
	"AP_PATERNO" VARCHAR2(100 BYTE), 
	"AP_MATERNO" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"MAIL" VARCHAR2(100 BYTE), 
	"TELEFONO" VARCHAR2(50 BYTE), 
	"COD_SUCURSAL" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EMPRESA_TARJETA
--------------------------------------------------------

  CREATE TABLE "EMPRESA_TARJETA" 
   (	"COD_EMP_TARJETA" NUMBER(*,0), 
	"EMP_TARJETA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table INTERES_FIJO
--------------------------------------------------------

  CREATE TABLE "INTERES_FIJO" 
   (	"MONTO_INF" NUMBER, 
	"MONTO_SUP" NUMBER, 
	"INTERES" NUMBER(8,2), 
	"COD_TIPO_CREDITO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table MOVIMIENTOS
--------------------------------------------------------

  CREATE TABLE "MOVIMIENTOS" 
   (	"ID_MOVIMIENTO" NUMBER(*,0), 
	"FECHA_MOVIMIENTO" DATE, 
	"COD_TIPO_MOVIMIENTO" NUMBER(*,0), 
	"MONTO" NUMBER(10,2), 
	"CARGO" NUMBER(10,2), 
	"ABONO" NUMBER(10,2), 
	"ID_CUENTA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PAGO_CREDITO
--------------------------------------------------------

  CREATE TABLE "PAGO_CREDITO" 
   (	"ID_PAGO" NUMBER(*,0), 
	"FECHA_VENCIMIENTO" DATE, 
	"NRO_CUOTA" NUMBER(*,0), 
	"FECHA_PAGO" DATE, 
	"MONTO" NUMBER(10,0), 
	"TOTAL_INTERES" NUMBER(10,0), 
	"TOTAL_COBRANZA" NUMBER(10,0), 
	"MONTO_PAGO" NUMBER(10,0), 
	"ID_CREDITO" NUMBER(*,0), 
	"RUT_CLIENTE" VARCHAR2(20 BYTE), 
	"TIPO_CREDITO" VARCHAR2(20 BYTE), 
	"COBRANZA_DIA" NUMBER(10,2), 
	"INTERES_DIA" NUMBER(10,2), 
	"NOMBRE_CLIENTE" VARCHAR2(200 BYTE), 
	"TIPO_CLIENTE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PESOS
--------------------------------------------------------

  CREATE TABLE "PESOS" 
   (	"MONTO_INF" NUMBER, 
	"MONTO_SUP" NUMBER, 
	"PESOS" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table PRODUCTO
--------------------------------------------------------

  CREATE TABLE "PRODUCTO" 
   (	"COD_PRODUCTO" NUMBER(*,0), 
	"PRODUCTO" VARCHAR2(100 BYTE), 
	"VALOR_MANTENCION" NUMBER(10,2), 
	"COD_TIPO_PRODUCTO" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SUCURSAL
--------------------------------------------------------

  CREATE TABLE "SUCURSAL" 
   (	"COD_SUCURSAL" NUMBER(*,0), 
	"SUCURSAL" VARCHAR2(100 BYTE), 
	"DIRECCION" VARCHAR2(100 BYTE), 
	"COD_COMUNA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TARJETA
--------------------------------------------------------

  CREATE TABLE "TARJETA" 
   (	"ID_TARJETA" NUMBER(*,0), 
	"NRO_TARJETA" NUMBER(10,0), 
	"VENCIMIENTO" DATE, 
	"CUPO" NUMBER(10,0), 
	"ID_CONTRATO" NUMBER(*,0), 
	"COD_PRODUCTO" NUMBER(*,0), 
	"COD_EMP_TARJETA" NUMBER(*,0), 
	"COD_TIPO_TARJETA" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_CLIENTE
--------------------------------------------------------

  CREATE TABLE "TIPO_CLIENTE" 
   (	"COD_TIPO_CLIENTE" NUMBER(*,0), 
	"TIPO_CLIENTE" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_CREDITO
--------------------------------------------------------

  CREATE TABLE "TIPO_CREDITO" 
   (	"COD_TIPO_CREDITO" NUMBER(*,0), 
	"TIPO_CREDITO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_CUENTA
--------------------------------------------------------

  CREATE TABLE "TIPO_CUENTA" 
   (	"COD_TIPO_CUENTA" NUMBER(*,0), 
	"TIPO_CUENTA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_MOVIMIENTO
--------------------------------------------------------

  CREATE TABLE "TIPO_MOVIMIENTO" 
   (	"COD_TIPO_MOVIMIENTO" NUMBER(*,0), 
	"TIPO_MOVIMIENTO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_PRODUCTO
--------------------------------------------------------

  CREATE TABLE "TIPO_PRODUCTO" 
   (	"COD_TIPO_PRODUCTO" NUMBER(*,0), 
	"TIPO_PRODUCTO" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TIPO_TARJETA
--------------------------------------------------------

  CREATE TABLE "TIPO_TARJETA" 
   (	"COD_TIPO_TARJETA" NUMBER(*,0), 
	"TIPO_TARJETA" VARCHAR2(100 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;